name: Test push every day

on:
  issues:
    types: [opened]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Send Push Notification
      uses: techulus/push-github-action@1.0.0
      env:
        API_KEY: ${{ secrets.PUSH_KEY }}
        MESSAGE: "A new status issue has been opened for theshadow.xyz!"
        TITLE: TheShadow.xyz
        LINK: https://github.com/thewilloftheshadow/status/issues
